### PR TITLE
Added typings and fix for message length error

### LINKED ISSUE #37: Missing Typings
Hey, 
great module. It would be even better with typings. 
Do you see a chance to add those?

Best

### PR DESCRIPTION
**Pull request by Exitare**
Added missing typings and added a fix to prevent discord rejecting the hook.
Closes #37 and #43 

The message check is only done for the first attachment and the first fields inside this attachment. If it is possible to add more attachments or fields, I will add this check aswell.

### CODE REVIEW

**Comment by jos-b** [comment]
This looks good apart from the fact that the functions in the message builder do not return void they return the instance of the message builder.

**Comment by Exitare** [comment]
kk, will fix it

**Comment by jos-b** [comment]
it is for chaining

**Comment by jos-b** [comment]
so you can do `builder.setDescription(...).setFooter(...)`

**Comment by Exitare** [comment]
@jos-b updates request

**Comment by jos-b** [comment]
Awesome, will get round to reviewing later, thanks!

File: index.d.ts [hunk 1]
```diff
@@ -0,0 +1,110 @@
...
+     *  @param {string} title The title of the custom webhook.
+     *  @param {string} color The color of the custom webhook. (optional)
+     *  @param {string} imageUrl The url of the image to attach (optional)
+     */
+    public custom(name: string, message: string, title: string, color: string, imageUrl: string): void;
+  }
+
+  // tslint:disable-next-line:max-classes-per-file
+  export class MessageBuilder {
+    constructor(name?: string, color?: string, text?: string, image?: string, time?: number);
```
Comment (jos-b) [inline index.d.ts]: The constructor does not take these in as parameters, they are not public either.

File: index.d.ts [hunk 2]
```diff
@@ -0,0 +1,110 @@
...
+    public warn(name: string, message: string): void;
+
+    /**
+     *  @param {string} name The username of the custom webhook.
+     *  @param {string} message The message of the custom webhook.
+     *  @param {string} title The title of the custom webhook.
+     *  @param {string} color The color of the custom webhook. (optional)
+     *  @param {string} imageUrl The url of the image to attach (optional)
+     */
+    public custom(name: string, message: string, title: string, color: string, imageUrl: string): void;
```
Comment (jos-b) [inline index.d.ts]: Do we even need typing on this? It's a deprecated method anyway since people should be using MessageBuilder.

Comment (Exitare) [reply index.d.ts]: Solved in 5e5fe18

File: index.d.ts (hunk 1 above)
Comment (Exitare) [reply index.d.ts]: Solved in 5e5fe18

Comment (Exitare) [reply index.d.ts]: And no, the module is working as it is. Checked it first on my side, while using it in prod environment

**Comment by Exitare** [comment]
Any updates on this?

File: lib/webhook.js [hunk 3]
```diff
@@ -41,13 +41,23 @@ class Webhook {
         }
     }
 
+     /**
+     * Check the message length, because discord is rejecting messages containing more than 1000 chararacters.
+     * @param {string} message 
+     */
+    checkMessageLength(message) {
+        if (message.length > 1000)
+            throw new Error(`The message given was ${message.length}. Discord webhook messages must be under 1000 characters`);
```
Comment (jos-b) [inline lib/webhook.js]: This isn't gramatically pretty. Please change to `The message given was ${message.length} characters, fields of Discord embeds must be under 1024 characters`. Also, it is 1024 chars instead of 1000.

Comment (Exitare) [reply lib/webhook.js]: Resolved by 11eafd8
